name: build

on:
  pull_request:
    branches:
    - main

jobs:
  bdist:
    name: create bdist
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install debian dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install -y dh-python python3 python3-stdeb python3-distutils python3-distutils-extra
    - name: Set up Virtual Environment
      run: |
        python -m venv .env
        source .env/bin/activate
    - name: Install dependencies
      run: |
        pip install stdeb wheel
        python setup.py develop --help
        python setup.py develop --version
    - name: bdist
      run: |
        python setup.py bdist
        python setup.py --command-packages=stdeb.command bdist_deb
        python setup.py bdist_rpm
    