name: build

on:
  push:
    tags:
      - "*"
  pull_request:
    branches:
    - main

jobs:
  bdist:
    name: create bdist
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install debian dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install -y dh-python python3 python3-stdeb python3-distutils python3-distutils-extra
    - name: Set up Virtual Environment
      run: |
        python -m venv .env
        source .env/bin/activate
    - name: Install dependencies
      run: |
        pip install stdeb wheel
        python setup.py develop --help
        python setup.py develop --version
    - name: bdist
      run: |
        python setup.py --command-packages=stdeb.command bdist_deb
        python setup.py bdist_rpm
    - name: get version
      id: version
      run: |
        version=$(python setup.py --version)
        echo "tag=${version}" >> $GITHUB_OUTPUT
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        body_path: "changelog/release-${{ steps.version.outputs.tag }}..d"
        fail_on_unmatched_files: true
        files: |
          LICENSE.txt
          ipv6ddns-*.tar.gz
          deb_dist/python3-ipv6ddns*.deb
          dist/ipv6ddns*.rpm

    