name: build

on:
  pull_request:
    branches:
    - main

jobs:
  bdist:
    name: create bdist
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Create 
      run: |
        python setup.py bdist
  
  deb:
    name: create deb
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install debian dependencies
      run: |
        python -m pip install --upgrade pip
        apt-get install -y dh-python python3-stdeb
        pip install stdeb wheel
    - name: Create 
      run: |
        python setup.py --command-packages=stdeb.command bdist_deb
  
  # rpm:
  #   name: create rpm
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Set up Python 3.11
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: '3.11'
  #   - name: Install debian dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       apt-get install -y dh-python python3-stdeb
  #       pip install stdeb wheel
  #   - name: Create 
  #     run: |
  #       python setup.py --command-packages=stdeb.command bdist_deb
    