name: build

on:
  pull_request:
    branches:
    - main

jobs:
  bdist:
    name: create bdist
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Create 
      run: |
        python setup.py bdist
  
  deb:
    name: create deb
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install debian dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install -y dh-python python3 python3-stdeb python3-distutils python3-distutils-extra
    - name: Set up Virtual Environment
      run: |
        python -m venv .env
        source .env/bin/activate
    - name: Install dependencies
      run: |
        pip install stdeb wheel
        python setup.py develop --help
        python setup.py develop --version
    - name: Create 
      run: |
        python setup.py --command-packages=stdeb.command bdist_deb
      env:
        SETUPTOOLS_USE_DISTUTILS: stdlib
  
  rpm:
    name: create rpm
    runs-on: ubuntu-latest
    container:
      image: centos:7
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Create 
      run: |
        python setup.py bdist_rpm
    