name: pylint and test

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')

  test:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Virtual Environment
      run: |
        python -m venv .env
        source .env/bin/activate
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
    - name: Install project
      run: |
        python setup.py install
        python ipv6ddns_dns_route53/setup.py install
    - name: Test
      run: |
        python -m pytest
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      if: ${{ github.event_name == 'push' && matrix.python-version == '3.11' }}
      env: 
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
